# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Beginner(object):
    def setupUi(self, Beginner):
        Beginner.setObjectName("Beginner")
        Beginner.resize(729, 524)
        Beginner.setMinimumSize(QtCore.QSize(729, 524))
        Beginner.setMaximumSize(QtCore.QSize(729, 524))
        font = QtGui.QFont()
        font.setPointSize(11)
        Beginner.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/40782.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Beginner.setWindowIcon(icon)
        Beginner.setWindowOpacity(1.0)
        Beginner.setStyleSheet("")
        self.Menu = QtWidgets.QPushButton(Beginner)
        self.Menu.setGeometry(QtCore.QRect(0, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        self.Menu.setFont(font)
        self.Menu.setStyleSheet("QPushButton {\n"
"    background-color:rgb(130, 130, 130);\n"
"    color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"    \n"
"")
        self.Menu.setObjectName("Menu")
        self.restart_game = QtWidgets.QPushButton(Beginner)
        self.restart_game.setGeometry(QtCore.QRect(340, 110, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.restart_game.setFont(font)
        self.restart_game.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"    ")
        self.restart_game.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/2341813.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restart_game.setIcon(icon1)
        self.restart_game.setIconSize(QtCore.QSize(30, 30))
        self.restart_game.setObjectName("restart_game")
        self.label = QtWidgets.QLabel(Beginner)
        self.label.setGeometry(QtCore.QRect(220, 10, 271, 71))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Beginner)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Kristen ITC\";\n"
"")
        self.label_2.setVisible(False)
        self.label_2.setObjectName("label_2")
        self.lcdMines = QtWidgets.QLCDNumber(Beginner)
        self.lcdMines.setGeometry(QtCore.QRect(240, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lcdMines.setFont(font)
        self.lcdMines.setStyleSheet("")
        self.lcdMines.setLineWidth(1)
        self.lcdMines.setMidLineWidth(1)
        self.lcdMines.setProperty("intValue", 10)
        self.lcdMines.setObjectName("lcdMines")
        self.lcdTime = QtWidgets.QLCDNumber(Beginner)
        self.lcdTime.setGeometry(QtCore.QRect(410, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lcdTime.setFont(font)
        self.lcdTime.setLineWidth(1)
        self.lcdTime.setMidLineWidth(1)
        self.lcdTime.setProperty("intValue", 0)
        self.lcdTime.setObjectName("lcdTime")
        self.pushButton_59 = QtWidgets.QPushButton(Beginner)
        self.pushButton_59.setGeometry(QtCore.QRect(389, 396, 34, 23))
        self.pushButton_59.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_59.setText("")
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_16 = QtWidgets.QPushButton(Beginner)
        self.pushButton_16.setGeometry(QtCore.QRect(468, 216, 34, 23))
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_75 = QtWidgets.QPushButton(Beginner)
        self.pushButton_75.setGeometry(QtCore.QRect(310, 468, 34, 23))
        self.pushButton_75.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_75.setText("")
        self.pushButton_75.setObjectName("pushButton_75")
        self.pushButton_9 = QtWidgets.QPushButton(Beginner)
        self.pushButton_9.setGeometry(QtCore.QRect(192, 216, 33, 23))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_57 = QtWidgets.QPushButton(Beginner)
        self.pushButton_57.setGeometry(QtCore.QRect(310, 396, 34, 23))
        self.pushButton_57.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_57.setText("")
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_36 = QtWidgets.QPushButton(Beginner)
        self.pushButton_36.setGeometry(QtCore.QRect(192, 324, 33, 23))
        self.pushButton_36.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_36.setText("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_61 = QtWidgets.QPushButton(Beginner)
        self.pushButton_61.setGeometry(QtCore.QRect(468, 396, 34, 23))
        self.pushButton_61.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_61.setText("")
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_68 = QtWidgets.QPushButton(Beginner)
        self.pushButton_68.setGeometry(QtCore.QRect(389, 432, 34, 23))
        self.pushButton_68.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_68.setText("")
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_46 = QtWidgets.QPushButton(Beginner)
        self.pushButton_46.setGeometry(QtCore.QRect(231, 360, 34, 23))
        self.pushButton_46.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_46.setText("")
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_55 = QtWidgets.QPushButton(Beginner)
        self.pushButton_55.setGeometry(QtCore.QRect(231, 396, 34, 23))
        self.pushButton_55.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_55.setText("")
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_32 = QtWidgets.QPushButton(Beginner)
        self.pushButton_32.setGeometry(QtCore.QRect(389, 288, 34, 23))
        self.pushButton_32.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_32.setText("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_28 = QtWidgets.QPushButton(Beginner)
        self.pushButton_28.setGeometry(QtCore.QRect(231, 288, 34, 23))
        self.pushButton_28.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_28.setText("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_21 = QtWidgets.QPushButton(Beginner)
        self.pushButton_21.setGeometry(QtCore.QRect(310, 252, 34, 23))
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Beginner)
        self.pushButton_22.setGeometry(QtCore.QRect(350, 252, 33, 23))
        self.pushButton_22.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_35 = QtWidgets.QPushButton(Beginner)
        self.pushButton_35.setGeometry(QtCore.QRect(508, 288, 33, 23))
        self.pushButton_35.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_35.setText("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_80 = QtWidgets.QPushButton(Beginner)
        self.pushButton_80.setGeometry(QtCore.QRect(508, 468, 33, 23))
        self.pushButton_80.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_80.setText("")
        self.pushButton_80.setObjectName("pushButton_80")
        self.pushButton_12 = QtWidgets.QPushButton(Beginner)
        self.pushButton_12.setGeometry(QtCore.QRect(310, 216, 34, 23))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_25 = QtWidgets.QPushButton(Beginner)
        self.pushButton_25.setGeometry(QtCore.QRect(468, 252, 34, 23))
        self.pushButton_25.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_25.setText("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_76 = QtWidgets.QPushButton(Beginner)
        self.pushButton_76.setGeometry(QtCore.QRect(350, 468, 33, 23))
        self.pushButton_76.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_76.setText("")
        self.pushButton_76.setObjectName("pushButton_76")
        self.pushButton_45 = QtWidgets.QPushButton(Beginner)
        self.pushButton_45.setGeometry(QtCore.QRect(192, 360, 33, 23))
        self.pushButton_45.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_45.setText("")
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_0 = QtWidgets.QPushButton(Beginner)
        self.pushButton_0.setGeometry(QtCore.QRect(192, 180, 33, 23))
        self.pushButton_0.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"    ")
        self.pushButton_0.setText("")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_14 = QtWidgets.QPushButton(Beginner)
        self.pushButton_14.setGeometry(QtCore.QRect(389, 216, 34, 23))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_73 = QtWidgets.QPushButton(Beginner)
        self.pushButton_73.setGeometry(QtCore.QRect(231, 468, 34, 23))
        self.pushButton_73.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_73.setText("")
        self.pushButton_73.setObjectName("pushButton_73")
        self.pushButton_6 = QtWidgets.QPushButton(Beginner)
        self.pushButton_6.setGeometry(QtCore.QRect(429, 180, 33, 23))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_38 = QtWidgets.QPushButton(Beginner)
        self.pushButton_38.setGeometry(QtCore.QRect(271, 324, 33, 23))
        self.pushButton_38.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_38.setText("")
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(Beginner)
        self.pushButton_39.setGeometry(QtCore.QRect(310, 324, 34, 23))
        self.pushButton_39.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_39.setText("")
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_13 = QtWidgets.QPushButton(Beginner)
        self.pushButton_13.setGeometry(QtCore.QRect(350, 216, 33, 23))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"    \n"
"")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_64 = QtWidgets.QPushButton(Beginner)
        self.pushButton_64.setGeometry(QtCore.QRect(231, 432, 34, 23))
        self.pushButton_64.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_64.setText("")
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_50 = QtWidgets.QPushButton(Beginner)
        self.pushButton_50.setGeometry(QtCore.QRect(389, 360, 34, 23))
        self.pushButton_50.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_50.setText("")
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_54 = QtWidgets.QPushButton(Beginner)
        self.pushButton_54.setGeometry(QtCore.QRect(192, 396, 33, 23))
        self.pushButton_54.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_54.setText("")
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_66 = QtWidgets.QPushButton(Beginner)
        self.pushButton_66.setGeometry(QtCore.QRect(310, 432, 34, 23))
        self.pushButton_66.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_66.setText("")
        self.pushButton_66.setObjectName("pushButton_66")
        self.pushButton_67 = QtWidgets.QPushButton(Beginner)
        self.pushButton_67.setGeometry(QtCore.QRect(350, 432, 33, 23))
        self.pushButton_67.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_67.setText("")
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_63 = QtWidgets.QPushButton(Beginner)
        self.pushButton_63.setGeometry(QtCore.QRect(192, 432, 33, 23))
        self.pushButton_63.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_63.setText("")
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_23 = QtWidgets.QPushButton(Beginner)
        self.pushButton_23.setGeometry(QtCore.QRect(389, 252, 34, 23))
        self.pushButton_23.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_17 = QtWidgets.QPushButton(Beginner)
        self.pushButton_17.setGeometry(QtCore.QRect(508, 216, 33, 23))
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_27 = QtWidgets.QPushButton(Beginner)
        self.pushButton_27.setGeometry(QtCore.QRect(192, 288, 33, 23))
        self.pushButton_27.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_27.setText("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_18 = QtWidgets.QPushButton(Beginner)
        self.pushButton_18.setGeometry(QtCore.QRect(192, 252, 33, 23))
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_8 = QtWidgets.QPushButton(Beginner)
        self.pushButton_8.setGeometry(QtCore.QRect(508, 180, 33, 23))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_33 = QtWidgets.QPushButton(Beginner)
        self.pushButton_33.setGeometry(QtCore.QRect(429, 288, 33, 23))
        self.pushButton_33.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_33.setText("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_43 = QtWidgets.QPushButton(Beginner)
        self.pushButton_43.setGeometry(QtCore.QRect(468, 324, 34, 23))
        self.pushButton_43.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_43.setText("")
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_26 = QtWidgets.QPushButton(Beginner)
        self.pushButton_26.setGeometry(QtCore.QRect(508, 252, 33, 23))
        self.pushButton_26.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_26.setText("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_48 = QtWidgets.QPushButton(Beginner)
        self.pushButton_48.setGeometry(QtCore.QRect(310, 360, 34, 23))
        self.pushButton_48.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_48.setText("")
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_2 = QtWidgets.QPushButton(Beginner)
        self.pushButton_2.setGeometry(QtCore.QRect(271, 180, 33, 23))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_40 = QtWidgets.QPushButton(Beginner)
        self.pushButton_40.setGeometry(QtCore.QRect(350, 324, 33, 23))
        self.pushButton_40.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_40.setText("")
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_31 = QtWidgets.QPushButton(Beginner)
        self.pushButton_31.setGeometry(QtCore.QRect(350, 288, 33, 23))
        self.pushButton_31.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_31.setText("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_1 = QtWidgets.QPushButton(Beginner)
        self.pushButton_1.setGeometry(QtCore.QRect(231, 180, 34, 23))
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_56 = QtWidgets.QPushButton(Beginner)
        self.pushButton_56.setGeometry(QtCore.QRect(271, 396, 33, 23))
        self.pushButton_56.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_56.setText("")
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_71 = QtWidgets.QPushButton(Beginner)
        self.pushButton_71.setGeometry(QtCore.QRect(508, 432, 33, 23))
        self.pushButton_71.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_71.setText("")
        self.pushButton_71.setObjectName("pushButton_71")
        self.pushButton_77 = QtWidgets.QPushButton(Beginner)
        self.pushButton_77.setGeometry(QtCore.QRect(389, 468, 34, 23))
        self.pushButton_77.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_77.setText("")
        self.pushButton_77.setObjectName("pushButton_77")
        self.pushButton_65 = QtWidgets.QPushButton(Beginner)
        self.pushButton_65.setGeometry(QtCore.QRect(271, 432, 33, 23))
        self.pushButton_65.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_65.setText("")
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_78 = QtWidgets.QPushButton(Beginner)
        self.pushButton_78.setGeometry(QtCore.QRect(429, 468, 33, 23))
        self.pushButton_78.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_78.setText("")
        self.pushButton_78.setObjectName("pushButton_78")
        self.pushButton_10 = QtWidgets.QPushButton(Beginner)
        self.pushButton_10.setGeometry(QtCore.QRect(231, 216, 34, 23))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_5 = QtWidgets.QPushButton(Beginner)
        self.pushButton_5.setGeometry(QtCore.QRect(389, 180, 34, 23))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(Beginner)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 180, 33, 23))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_34 = QtWidgets.QPushButton(Beginner)
        self.pushButton_34.setGeometry(QtCore.QRect(468, 288, 34, 23))
        self.pushButton_34.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_34.setText("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_69 = QtWidgets.QPushButton(Beginner)
        self.pushButton_69.setGeometry(QtCore.QRect(429, 432, 33, 23))
        self.pushButton_69.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_69.setText("")
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_3 = QtWidgets.QPushButton(Beginner)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 180, 34, 23))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_29 = QtWidgets.QPushButton(Beginner)
        self.pushButton_29.setGeometry(QtCore.QRect(271, 288, 33, 23))
        self.pushButton_29.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}")
        self.pushButton_29.setText("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_19 = QtWidgets.QPushButton(Beginner)
        self.pushButton_19.setGeometry(QtCore.QRect(231, 252, 34, 23))
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_74 = QtWidgets.QPushButton(Beginner)
        self.pushButton_74.setGeometry(QtCore.QRect(271, 468, 33, 23))
        self.pushButton_74.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_74.setText("")
        self.pushButton_74.setObjectName("pushButton_74")
        self.pushButton_72 = QtWidgets.QPushButton(Beginner)
        self.pushButton_72.setGeometry(QtCore.QRect(192, 468, 33, 23))
        self.pushButton_72.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_72.setText("")
        self.pushButton_72.setObjectName("pushButton_72")
        self.pushButton_58 = QtWidgets.QPushButton(Beginner)
        self.pushButton_58.setGeometry(QtCore.QRect(350, 396, 33, 23))
        self.pushButton_58.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_58.setText("")
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_20 = QtWidgets.QPushButton(Beginner)
        self.pushButton_20.setGeometry(QtCore.QRect(271, 252, 33, 23))
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_30 = QtWidgets.QPushButton(Beginner)
        self.pushButton_30.setGeometry(QtCore.QRect(310, 288, 34, 23))
        self.pushButton_30.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_30.setText("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_47 = QtWidgets.QPushButton(Beginner)
        self.pushButton_47.setGeometry(QtCore.QRect(271, 360, 33, 23))
        self.pushButton_47.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_47.setText("")
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_37 = QtWidgets.QPushButton(Beginner)
        self.pushButton_37.setGeometry(QtCore.QRect(231, 324, 34, 23))
        self.pushButton_37.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_37.setText("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_79 = QtWidgets.QPushButton(Beginner)
        self.pushButton_79.setGeometry(QtCore.QRect(468, 468, 34, 23))
        self.pushButton_79.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_79.setText("")
        self.pushButton_79.setObjectName("pushButton_79")
        self.pushButton_42 = QtWidgets.QPushButton(Beginner)
        self.pushButton_42.setGeometry(QtCore.QRect(429, 324, 33, 23))
        self.pushButton_42.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_42.setText("")
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_70 = QtWidgets.QPushButton(Beginner)
        self.pushButton_70.setGeometry(QtCore.QRect(468, 432, 34, 23))
        self.pushButton_70.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_70.setText("")
        self.pushButton_70.setObjectName("pushButton_70")
        self.pushButton_11 = QtWidgets.QPushButton(Beginner)
        self.pushButton_11.setGeometry(QtCore.QRect(271, 216, 33, 23))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"    \n"
"")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_7 = QtWidgets.QPushButton(Beginner)
        self.pushButton_7.setGeometry(QtCore.QRect(468, 180, 34, 23))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_62 = QtWidgets.QPushButton(Beginner)
        self.pushButton_62.setGeometry(QtCore.QRect(508, 396, 33, 23))
        self.pushButton_62.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_62.setText("")
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_60 = QtWidgets.QPushButton(Beginner)
        self.pushButton_60.setGeometry(QtCore.QRect(429, 396, 33, 23))
        self.pushButton_60.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_60.setText("")
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_53 = QtWidgets.QPushButton(Beginner)
        self.pushButton_53.setGeometry(QtCore.QRect(508, 360, 33, 23))
        self.pushButton_53.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_53.setText("")
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_51 = QtWidgets.QPushButton(Beginner)
        self.pushButton_51.setGeometry(QtCore.QRect(429, 360, 33, 23))
        self.pushButton_51.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_51.setText("")
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_44 = QtWidgets.QPushButton(Beginner)
        self.pushButton_44.setGeometry(QtCore.QRect(508, 324, 33, 23))
        self.pushButton_44.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_44.setText("")
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_41 = QtWidgets.QPushButton(Beginner)
        self.pushButton_41.setGeometry(QtCore.QRect(389, 324, 34, 23))
        self.pushButton_41.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_41.setText("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_24 = QtWidgets.QPushButton(Beginner)
        self.pushButton_24.setGeometry(QtCore.QRect(429, 252, 33, 23))
        self.pushButton_24.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_15 = QtWidgets.QPushButton(Beginner)
        self.pushButton_15.setGeometry(QtCore.QRect(429, 216, 33, 23))
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"    \n"
"")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_52 = QtWidgets.QPushButton(Beginner)
        self.pushButton_52.setGeometry(QtCore.QRect(468, 360, 34, 23))
        self.pushButton_52.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_52.setText("")
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_49 = QtWidgets.QPushButton(Beginner)
        self.pushButton_49.setGeometry(QtCore.QRect(350, 360, 33, 23))
        self.pushButton_49.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 115);\n"
"}\n"
"\n"
"")
        self.pushButton_49.setText("")
        self.pushButton_49.setObjectName("pushButton_49")

        self.retranslateUi(Beginner)
        QtCore.QMetaObject.connectSlotsByName(Beginner)

    def retranslateUi(self, Beginner):
        _translate = QtCore.QCoreApplication.translate
        Beginner.setWindowTitle(_translate("Beginner", "Beginner game"))
        self.Menu.setText(_translate("Beginner", "Menu"))
        self.label_2.setWhatsThis(_translate("Beginner", "<html><head/><body><p align=\"center\">Game over!</p></body></html>"))
        self.label_2.setText(_translate("Beginner", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffffff;\">Game over!</span></p></body></html>"))
