# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(729, 524)
        MainWindow.setMinimumSize(QtCore.QSize(729, 524))
        MainWindow.setMaximumSize(QtCore.QSize(729, 524))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_beginner = QtWidgets.QPushButton(self.centralwidget)
        self.btn_beginner.setGeometry(QtCore.QRect(270, 230, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_beginner.setFont(font)
        self.btn_beginner.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 68, 102);\n"
"}\n"
"")
        self.btn_beginner.setObjectName("btn_beginner")
        self.btn_rules = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rules.setGeometry(QtCore.QRect(270, 180, 191, 31))
        self.btn_rules.setMinimumSize(QtCore.QSize(191, 31))
        self.btn_rules.setMaximumSize(QtCore.QSize(191, 31))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_rules.setFont(font)
        self.btn_rules.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 68, 102);\n"
"}\n"
"\n"
"")
        self.btn_rules.setObjectName("btn_rules")
        self.btn_interm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_interm.setGeometry(QtCore.QRect(270, 280, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_interm.setFont(font)
        self.btn_interm.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 68, 102);\n"
"}\n"
"")
        self.btn_interm.setObjectName("btn_interm")
        self.btn_expert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_expert.setGeometry(QtCore.QRect(270, 330, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_expert.setFont(font)
        self.btn_expert.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 68, 102);\n"
"}\n"
"")
        self.btn_expert.setObjectName("btn_expert")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(270, 380, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(102, 68, 102);\n"
"}\n"
"")
        self.btn_exit.setObjectName("btn_exit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " Game"))
        MainWindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffaaff;\">Welcome to the game minesweeper!</span></p></body></html>"))
        self.btn_beginner.setText(_translate("MainWindow", "Beginner"))
        self.btn_rules.setText(_translate("MainWindow", "Rules"))
        self.btn_interm.setText(_translate("MainWindow", "Intermediate"))
        self.btn_expert.setText(_translate("MainWindow", "Expert"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
