# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Win_window(object):
    def setupUi(self, Win_window):
        Win_window.setObjectName("Win_window")
        Win_window.resize(496, 358)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/40782.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Win_window.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Win_window)
        self.buttonBox.setGeometry(QtCore.QRect(120, 310, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Win_window)
        self.label.setGeometry(QtCore.QRect(60, 90, 141, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/5201363.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Win_window)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 201, 51))
        self.label_2.setStyleSheet("font: 18pt \"Kristen ITC\";\n"
"color: rgb(255, 170, 0);")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Win_window)
        self.label_6.setGeometry(QtCore.QRect(240, 200, 124, 25))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Win_window)
        self.label_7.setGeometry(QtCore.QRect(240, 240, 124, 25))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Win_window)
        self.label_5.setGeometry(QtCore.QRect(240, 150, 191, 43))
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Win_window)
        self.label_4.setGeometry(QtCore.QRect(240, 110, 53, 25))
        self.label_4.setObjectName("label_4")
        self.label_time1 = QtWidgets.QLabel(Win_window)
        self.label_time1.setGeometry(QtCore.QRect(300, 110, 243, 25))
        self.label_time1.setObjectName("label_time1")
        self.label_3 = QtWidgets.QLabel(Win_window)
        self.label_3.setGeometry(QtCore.QRect(240, 70, 249, 29))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_time2 = QtWidgets.QLabel(Win_window)
        self.label_time2.setGeometry(QtCore.QRect(300, 200, 243, 25))
        self.label_time2.setObjectName("label_time2")
        self.label_date = QtWidgets.QLabel(Win_window)
        self.label_date.setGeometry(QtCore.QRect(300, 240, 243, 25))
        self.label_date.setObjectName("label_date")

        self.retranslateUi(Win_window)
        self.buttonBox.accepted.connect(Win_window.accept) # type: ignore
        self.buttonBox.rejected.connect(Win_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Win_window)

    def retranslateUi(self, Win_window):
        _translate = QtCore.QCoreApplication.translate
        Win_window.setWindowTitle(_translate("Win_window", "Victory"))
        self.label_2.setText(_translate("Win_window", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">You won!</span></p></body></html>"))
        self.label_6.setText(_translate("Win_window", "<html><head/><body><p><span style=\" font-size:16pt;\">Time:</span></p></body></html>"))
        self.label_7.setText(_translate("Win_window", "<html><head/><body><p><span style=\" font-size:16pt;\">Date:</span></p></body></html>"))
        self.label_5.setText(_translate("Win_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Your best result:</span></p></body></html>"))
        self.label_4.setText(_translate("Win_window", "<html><head/><body><p><span style=\" font-size:16pt;\">Time:</span></p></body></html>"))
        self.label_time1.setText(_translate("Win_window", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
        self.label_3.setText(_translate("Win_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Your result:</span></p></body></html>"))
        self.label_time2.setText(_translate("Win_window", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
        self.label_date.setText(_translate("Win_window", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
